apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
  - kind: ServiceAccount
    name: ken
    namespace: dev

