apiVersion: v1
kind: Pod
metadata:
  name: minio-client
spec:
  containers:
  - name: minio-client
    image: minio/mc
    envFrom:
    - secretRef:
        name: minio-credentials
    command: ["/bin/sh"]
    args: ["-c", "mc alias set minio http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY"]
  restartPolicy: Never
