apiVersion: v1
kind: Pod
metadata:
  name: web
  # labels:
  #   key: value 
spec:
  initContainers:
  - name: init-container
    image: busybox:stable
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  containers:
  - name: web
    image: bart08rus/my-app-nonroot:latest
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
    livenessProbe:
      tcpSocket:
        port: 8000
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
  - name: app
    emptyDir: {}